version: "3.9"

services:

  java_app_mov:
    container_name: java_app_mov
    image: mov
    build: .
    ports:
      - 5001:5001
    environment:
      - DATABASE_URL=jdbc:mysql://host.docker.internal:3306/bankingClient?createDatabaseIfNotExist=true
      - DATABASE_USERNAME=root
      - DATABASE_PASSWORD=admin12345
    depends_on:
      - mysql
      - java_app_client
    networks:
      - banking_net

  java_app_client:
    container_name: java_app_client
    image: client
    build: .
    ports:
      - 5000:5000
    environment:
      - DATABASE_URL=jdbc:mysql://host.docker.internal:3306/bankingClient?createDatabaseIfNotExist=true
      - DATABASE_USERNAME=root
      - DATABASE_PASSWORD=admin12345
      - KAFKA_SERVERS=kafka:9092
    depends_on:
      - mysql
    networks:
      - banking_net

  zookeeper:
    image: bitnami/zookeeper:latest
    ports:
      - "2181:2181"
    volumes:
      - "zookeeper_data:/bitnami"
    environment:
      - ALLOW_ANONYMOUS_LOGIN=yes
    networks:
      - banking_net

  kafka:
    image: bitnami/kafka:latest
    ports:
      - "9092:9092"
    volumes:
      - "kafka_data:/bitnami"
    environment:
      - KAFKA_ZOOKEEPER_CONNECT=zookeeper:2181
      - ALLOW_PLAINTEXT_LISTENER=yes
      - KAFKA_LISTENERS=PLAINTEXT://:9092
      - KAFKA_ADVERTISED_LISTENERS=PLAINTEXT://host.docker.internal:9092
    depends_on:
      - zookeeper
    networks:
      - banking_net

  mysql:
    image: mysql:8.0.34
    environment:
      MYSQL_DATABASE: 'db'
      MYSQL_USER: 'dba_user'
      MYSQL_PASSWORD: 'admin12345'
      MYSQL_ROOT_PASSWORD: 'admin12345'
    ports:
      - '3306:3306'
    expose:
      - '3306'
    volumes:
      - type: bind
        source: ./shared/mysql_data
        target: /var/lib/mysql
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql
    networks:
      - banking_net

networks:
  banking_net:
    driver: bridge

volumes:
  zookeeper_data:
    driver: local

  kafka_data:
    driver: local

  mysql_data:
    driver: local